using System.Collections.Generic;
using ImpactTheory.Core.Logging;
using ImpactTheory.Physics;
using ImpactTheory.Runtime.Core;
using UnityEngine;

namespace ImpactTheory.Runtime.Physics
{
    /// <summary>
    /// Applies <see cref="PhysicsConfig"/> to Unity's physics world.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Configuration is applied from code rather than left to the values saved in
    /// <c>ProjectSettings/DynamicsManager.asset</c>. Two reasons, both practical.
    /// </para>
    /// <para>
    /// First, <c>Docs/Physics.md</c> §10 requires every tunable to live in one enumerable place, so
    /// that <c>VAL-014</c> can compare behaviour against a recorded baseline and
    /// <c>PhysicsConfigVersion</c> means something specific. A value that lives in a project
    /// settings asset is a value that can be changed in the inspector without anyone noticing it
    /// changed.
    /// </para>
    /// <para>
    /// Second, it makes the configuration survive the project being recreated. The editor is not
    /// installed yet (<c>ISSUE-001</c>), so <c>ProjectSettings/</c> will be generated by whoever
    /// opens the project first, with Unity's defaults - 0.02 s timestep and 6 solver iterations,
    /// neither of which suits a stacking puzzle with a 30 m/s projectile.
    /// </para>
    /// </remarks>
    public static class PhysicsBootstrap
    {
        private static PhysicsConfig _active;

        /// <summary>The configuration currently applied to the physics world.</summary>
        public static PhysicsConfig Active => _active ?? (_active = new PhysicsConfig());

        /// <summary>Pushes the configuration into Unity and records what was applied.</summary>
        public static void Apply(PhysicsConfig config)
        {
            _active = config ?? new PhysicsConfig();

            UnityEngine.Physics.gravity = _active.Gravity.ToUnity();
            UnityEngine.Physics.defaultSolverIterations = _active.SolverIterations;
            UnityEngine.Physics.defaultSolverVelocityIterations = _active.SolverVelocityIterations;

            Time.fixedDeltaTime = _active.FixedTimestep;

            // Unity's own sleep threshold is a related but separate mechanism from Impact Theory's
            // settling rule (Docs/Physics.md section 7). Dropping it below the game's linear
            // threshold stops Unity from parking a body that the game still considers in motion,
            // which would otherwise make a shot resolve while a piece was visibly creeping.
            UnityEngine.Physics.sleepThreshold = 0.005f;

            Log.PhysicsConfigVersion = _active.PhysicsConfigVersion;

            Log.Info(LogCategory.Physics, "physics configuration applied", new Dictionary<string, string>
            {
                { "config", _active.Describe() },
                { "sleepThreshold", UnityEngine.Physics.sleepThreshold.ToString("0.####") },
            });
        }

        /// <summary>
        /// Builds a Unity physics material for a family.
        /// </summary>
        /// <remarks>
        /// Created from the table rather than authored as assets, so friction and restitution can
        /// never drift between what a prefab says and what <see cref="MaterialPhysics"/> says.
        /// <c>Docs/Physics.md</c> §5: "never set inline on a prefab".
        /// <para>
        /// <c>Multiply</c> is the combine mode for friction so that a low-friction piece stays
        /// slippery against a grippy one, and <c>Maximum</c> for bounce so that a rubber roller
        /// bounces off concrete rather than being damped to nothing by it.
        /// </para>
        /// </remarks>
        public static PhysicsMaterial CreateMaterial(MaterialPhysics material)
        {
            PhysicsMaterial unityMaterial = new PhysicsMaterial(material.Family.ToString())
            {
                staticFriction = material.StaticFriction,
                dynamicFriction = material.DynamicFriction,
                bounciness = material.Restitution,
                frictionCombine = PhysicsMaterialCombine.Multiply,
                bounceCombine = PhysicsMaterialCombine.Maximum,
            };

            return unityMaterial;
        }
    }
}
